/**
 * Marked regions — how press owns part of a file without owning the file.
 *
 * A consumer's brand file is mostly hand-written, medium-specific code: a
 * 250-line stylesheet, a poster's geometry, a résumé's layout. Only the token
 * block and its loader are shared. So press splices a *marked region* into an
 * otherwise untouched file rather than generating the file, which is also what
 * keeps a whole-file sync from clobbering hand-written work (the personal avatar
 * footer in ghostwriter's diagram.css was lost that way once already).
 *
 * The start marker carries a receipt — the press version and a hash of the body
 * — so a hand-edit inside the region is detectable without re-running the
 * emitter, and so a diff shows *which* release last wrote it.
 */
import { createHash } from 'node:crypto';

/** Comment syntaxes a region can be expressed in. */
export const SYNTAXES = {
  python: { prefix: '# ', suffix: '' },
  // Byte-identical to `python`, and deliberately a separate entry: a workflow
  // file declaring `syntax: "python"` reads as a mistake to the next person
  // editing targets.json, and the day a YAML-specific quirk appears there is
  // nowhere to put it. The cost of the duplicate is three lines.
  yaml: { prefix: '# ', suffix: '' },
  css: { prefix: '/* ', suffix: ' */' },
  md: { prefix: '<!-- ', suffix: ' -->' },
};

const BANNER = 'GENERATED by @natjswenson/press, do not edit';

export class RegionError extends Error {}

function syntaxOf(name) {
  const s = SYNTAXES[name];
  if (!s) {
    throw new RegionError(
      `unknown syntax "${name}" (expected one of: ${Object.keys(SYNTAXES).join(', ')})`,
    );
  }
  return s;
}

const wrap = (syntax, text) => `${syntax.prefix}${text}${syntax.suffix}`;

/**
 * The inner text of a comment line, or null when the line is not a comment in
 * this syntax. Trailing whitespace is tolerated; leading is not, because these
 * markers are always at column 0.
 */
function unwrap(syntax, line) {
  const trimmed = line.replace(/\s+$/, '');
  if (!trimmed.startsWith(syntax.prefix)) return null;
  if (syntax.suffix && !trimmed.endsWith(syntax.suffix)) return null;
  return trimmed.slice(syntax.prefix.length, trimmed.length - syntax.suffix.length);
}

/** Short, stable content hash of a region body. */
export function bodyHash(body) {
  const normalized = body.replace(/\r\n/g, '\n').replace(/\s+$/, '');
  return createHash('sha256').update(normalized, 'utf8').digest('hex').slice(0, 12);
}

export function startMarker(syntaxName, region, version, hash) {
  const syntax = syntaxOf(syntaxName);
  return wrap(syntax, `>>> press:${region} v${version} sha256:${hash} ${BANNER}`);
}

export function endMarker(syntaxName, region) {
  return wrap(syntaxOf(syntaxName), `<<< press:${region}`);
}

/**
 * Locate a region. Returns null when the file has no such region — callers
 * decide whether that is a migration opportunity (`emit --init`) or a failure
 * (`check`, where a vanished region must go red rather than silently pass).
 */
export function findRegion(text, region, syntaxName) {
  const syntax = syntaxOf(syntaxName);
  const lines = text.split('\n');
  const openRe = new RegExp(`^>>> press:${escapeRe(region)}(?:\\s|$)`);
  const closeRe = new RegExp(`^<<< press:${escapeRe(region)}\\s*$`);

  let start = -1;
  for (let i = 0; i < lines.length; i += 1) {
    const inner = unwrap(syntax, lines[i]);
    if (inner !== null && openRe.test(inner)) {
      if (start !== -1) {
        throw new RegionError(
          `region "${region}" opens twice (lines ${start + 1} and ${i + 1}) — a file may declare it only once`,
        );
      }
      start = i;
    }
  }
  if (start === -1) return null;

  let end = -1;
  for (let i = start + 1; i < lines.length; i += 1) {
    const inner = unwrap(syntax, lines[i]);
    if (inner !== null && closeRe.test(inner)) {
      end = i;
      break;
    }
  }
  if (end === -1) {
    throw new RegionError(
      `region "${region}" opens at line ${start + 1} but never closes — expected a line reading ${JSON.stringify(endMarker(syntaxName, region))}`,
    );
  }

  const openInner = unwrap(syntax, lines[start]);
  const receipt = /\bv(\S+)\s+sha256:([0-9a-f]+)/.exec(openInner);

  return {
    startLine: start,
    endLine: end,
    body: lines.slice(start + 1, end).join('\n'),
    version: receipt ? receipt[1] : null,
    hash: receipt ? receipt[2] : null,
  };
}

/** Rebuild the full marked block (start marker, body, end marker). */
export function renderRegion(region, syntaxName, body, version) {
  const trimmed = body.replace(/\s+$/, '');
  return [
    startMarker(syntaxName, region, version, bodyHash(trimmed)),
    trimmed,
    endMarker(syntaxName, region),
  ].join('\n');
}

/** Replace an existing region's block in `text`. Throws if there isn't one. */
export function spliceRegion(text, region, syntaxName, body, version) {
  const found = findRegion(text, region, syntaxName);
  if (!found) {
    throw new RegionError(
      `${text.length === 0 ? 'empty file' : 'file'} has no press:${region} region — run \`press emit --target <id> --init\` to create one`,
    );
  }
  const lines = text.split('\n');
  const block = renderRegion(region, syntaxName, body, version).split('\n');
  lines.splice(found.startLine, found.endLine - found.startLine + 1, ...block);
  return lines.join('\n');
}

/**
 * First-time insertion, for migrating a consumer that still carries a
 * hand-written copy.
 *
 * `anchor.replaceFrom`/`anchor.replaceTo` are regexes naming the first and last
 * line of the legacy span the region takes over, so the duplicate is swallowed
 * in the same operation rather than left behind to drift. With no anchor the
 * block is appended.
 */
export function initRegion(text, region, syntaxName, body, version, anchor = {}) {
  if (findRegion(text, region, syntaxName)) {
    throw new RegionError(`file already has a press:${region} region — use emit without --init`);
  }
  const block = renderRegion(region, syntaxName, body, version);
  const { replaceFrom, replaceTo, insertAfter } = anchor;

  // Seeding a brand-new region (a README badge) rather than taking over a
  // hand-written block: place it after the first line matching `insertAfter`,
  // usually the title, instead of appending to the bottom where nobody looks.
  if (insertAfter) {
    const lines = text.split('\n');
    const re = new RegExp(insertAfter);
    const at = lines.findIndex((l) => re.test(l));
    if (at === -1) throw new RegionError(`anchor insertAfter /${insertAfter}/ matched no line`);
    let i = at + 1;
    while (i < lines.length && lines[i].trim() === '') i += 1;
    lines.splice(i, 0, ...block.split('\n'), '');
    return lines.join('\n');
  }

  if (!replaceFrom) return `${text.replace(/\s+$/, '')}\n\n${block}\n`;

  const lines = text.split('\n');
  const fromRe = new RegExp(replaceFrom);
  const from = lines.findIndex((l) => fromRe.test(l));
  if (from === -1) {
    throw new RegionError(`anchor replaceFrom /${replaceFrom}/ matched no line`);
  }
  const toRe = new RegExp(replaceTo ?? replaceFrom);
  let to = -1;
  for (let i = from; i < lines.length; i += 1) {
    if (toRe.test(lines[i]) && (i > from || !replaceTo)) {
      to = i;
      break;
    }
  }
  if (to === -1) {
    throw new RegionError(`anchor replaceTo /${replaceTo}/ matched no line at or after line ${from + 1}`);
  }
  lines.splice(from, to - from + 1, ...block.split('\n'));
  return lines.join('\n');
}

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
