/**
 * Every byte a new skill starts life with.
 *
 * Pure functions: spec + house facts in, {path, content} out. No clock, no
 * network, no randomness — which is what lets the emitted tree be pinned
 * byte-exactly as a baseline, for the same reason shipflow pins its rendered
 * workflow and press pins its emitted regions. When the generated bytes ARE the
 * contract, one changed character is a change to every skill made after it.
 *
 * Two deliberate omissions from this file: the press masthead on the caller
 * workflow, and the press:agent-ui region in SKILL.md. Both are *stamped* after
 * the tree lands, by press and forge themselves. A brand value written down
 * here would be the ninth hand-ported copy of the thing press exists to end.
 */

const ORG = 'natejswenson';
const REPO = 'claude-skills';
const AUTHOR = 'Nate Swenson';
const NPM_SCOPE = '@natjswenson';

const j = (obj) => `${JSON.stringify(obj, null, 2)}\n`;

/* ------------------------------------------------------------------ plugin root */

export const license = (year) => `MIT License

Copyright (c) ${year} ${AUTHOR}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`;

/**
 * The README's first line is load-bearing: press's `<name>-readme` target
 * inserts its version region after `^# <name> `, so changing this heading
 * silently detaches the badge.
 */
export const readme = (spec) => `# ${spec.name} (Claude Code skill)

${spec.summary}

${spec.oneRule}

\`\`\`bash
${spec.commands.map((c) => `${spec.name} ${c.name}`).join('\n')}
\`\`\`

Install via the [${REPO} marketplace](https://github.com/${ORG}/${REPO}).
`;

export const changelog = (spec, today) => `# Changelog

All notable changes to the **${spec.name}** skill are documented here.

The format follows [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) and
this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [0.1.0] - ${today}

### Added

- First release. ${spec.summary}
`;

export const pluginJson = (spec) =>
  j({
    name: spec.name,
    version: '0.1.0',
    description: spec.summary,
    author: { name: AUTHOR },
    homepage: `https://github.com/${ORG}/${REPO}/tree/main/skills/${spec.name}`,
    license: 'MIT',
  });

/* ------------------------------------------------------------------ inner skill */

export const packageJson = (spec) =>
  j({
    name: `${NPM_SCOPE}/${spec.name}`,
    version: '0.1.0',
    description: spec.summary,
    license: 'MIT',
    author: AUTHOR,
    homepage: `https://github.com/${ORG}/${REPO}`,
    repository: { type: 'git', url: `git+https://github.com/${ORG}/${REPO}.git` },
    bugs: { url: `https://github.com/${ORG}/${REPO}/issues` },
    keywords: [spec.name, 'claude-code', 'claude-skill'],
    type: 'module',
    bin: { [spec.name]: `scripts/${spec.name}.js` },
    files: ['scripts/', 'references/', 'skill-invariants.json', 'SKILL.md', 'CHANGELOG.md', 'README.md', 'LICENSE'],
    engines: { node: '>=18' },
    scripts: {
      test: 'node --test "scripts/**/*.test.mjs"',
      audit: 'npm audit --audit-level=moderate',
      prepack: 'cp ../../README.md ../../LICENSE ../../CHANGELOG.md .',
      postpack: 'rm -f README.md LICENSE CHANGELOG.md',
    },
  });

/**
 * The SKILL.md skeleton. Every heading here is one the author step must fill —
 * it is a contract, not filler. The `<!-- press:agent-ui -->` anchor is where
 * `press emit --init` splices the run-presentation contract; the region is
 * never written by hand.
 */
export const skillMd = (spec) => {
  const cmdRows = spec.commands.map((c) => `| \`${spec.name} ${c.name}\` | ${c.does} |`).join('\n');
  const detRows = spec.split.deterministic.map((s) => `| ${s.step} | \`${s.command}\` |`).join('\n');
  const nonRows = spec.split.nondeterministic.map((s) => `| ${s.step} | ${s.why} |`).join('\n');
  const refRows = spec.references.map((r) => `| \`references/${r.file}\` | ${r.is} |`).join('\n');

  return `---
name: ${spec.name}
description: ${spec.description}
user_invocable: true
version: 0.1.0
---

# /${spec.name} — ${spec.summary.replace(/\.$/, '')}

You are running the **${spec.name}** skill.

**Announce at start:** "I'm using the ${spec.name} skill — ${spec.summary.replace(/\.$/, '')}."

> Commands below run from the directory containing this \`SKILL.md\` (\`$SKILL_DIR\`).
> Resolve it once. Pass \`--repo <path>\` to work against the user's repo.

## The one rule

**${spec.oneRule}**

## What is code and what is judgment

The split is declared in \`skill-invariants.json\` and checked — a deterministic
step whose command does not exist fails \`smith verify\`.

| Deterministic — the machine decides | Command |
|---|---|
${detRows}

| Model judgment — nothing on disk answers it | Why |
|---|---|
${nonRows}

## The flow

### 1. Detect — never ask what you can read

Run the detection command first and read its table. **Never ask about anything
in it.** A confirmation is not a question.

### 2. Ask at most two questions, one at a time

Opinionated, with a one-line reason. Zero questions is correct when the request
already answered them.

### 3. Do the work

${spec.commands.map((c) => `- \`${spec.name} ${c.name}\` — ${c.does}`).join('\n')}

### 4. Report

One table with a fixed column set, then one sentence, then stop.

## Commands

| Command | Returns |
|---|---|
${cmdRows}

## Rules that are not negotiable

- **${spec.oneRule}**
- **Never claim a result you did not observe.** Say what you verified and what
  you did not.

<!-- press:agent-ui -->

## What's here

| Path | Is |
|---|---|
| \`scripts/${spec.name}.js\` | the CLI: ${spec.commands.map((c) => `\`${c.name}\``).join(', ')} |
${refRows}

## Maintainer reference — not part of a user run

\`skill-invariants.json\` names what must not silently disappear, declares which
half of this skill is code, and lists the baseline eval set. The baseline is
pinned against a real run — see its \`update_command\` to refresh it.
`;
};

export const invariants = (spec) => {
  const prose = [
    {
      id: 'the-one-rule',
      // Slice BEFORE escaping. Escaping first and slicing after can cut a
      // two-character escape in half and produce a pattern that either throws
      // or silently matches something else.
      pattern: spec.oneRule.slice(0, 60).replace(/[.*+?^${}()|[\]\\]/g, '\\$&'),
      rationale:
        'The one rule. It is the reason this skill exists rather than a prompt; lose the line and the skill becomes a generic assistant with extra steps.',
    },
    {
      id: 'never-claim-an-unobserved-result',
      pattern: 'Never claim a result you did not observe',
      rationale:
        'Honesty about what was verified is the whole house contract. A skill that reports success it did not witness is worse than one that reports nothing.',
    },
    {
      id: 'detection-is-the-question-budget',
      pattern: 'never ask about anything in it',
      rationale:
        'Two questions maximum is only achievable because detection already answered the rest. Asking about a detectable signal is the UX failure that makes a skill feel like a form.',
    },
  ];

  return j({
    comment: `What must not silently disappear from ${spec.name}. \`prose\` names guardrails no code enforces; \`split\` declares which half of the skill is deterministic; \`baseline\` names the offline, $0 checks pinned against a real run.`,
    smith: { version: '0.1.0' },
    prose,
    split: spec.split,
    _baseline_comment:
      'Pinned against a real run of this skill, never a synthetic fixture. Offline and $0 by construction: no network, no model, so CI cannot spend and cannot flake.',
    baseline: spec.evalPlan.map((e) => ({
      id: e.id,
      kind: e.kind,
      test: 'scripts/tests/baseline.test.mjs',
      ...(e.kind === 'corpus'
        ? { corpus_glob: e.corpusGlob ?? 'evals/baseline/*', min_corpus: e.minCorpus ?? 1 }
        : { fixtures: e.fixtures ?? [] }),
      update_command: e.updateCommand ?? 'node evals/baseline/update.mjs',
      rationale: `${e.catches ?? 'degradation'} — pinned against ${e.pinnedAgainst}.`,
    })),
  });
};

/* ------------------------------------------------------------------ code */

export const cli = (spec) => `#!/usr/bin/env node
/**
 * ${spec.name} — the deterministic half of the skill.
 *
 * Everything mechanical lives here so the agent never reshapes output with
 * sed/grep/jq in the transcript: one command returns everything a step needs,
 * already as a table. The agent's job is the conversation; this binary's job
 * is facts.
 */
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const VERSION = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8')).version;

function argv(args) {
  const out = { _: [] };
  for (let i = 0; i < args.length; i += 1) {
    const a = args[i];
    if (a.startsWith('--')) {
      const [k, inline] = a.slice(2).split('=');
      const key = k.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
      if (inline !== undefined) out[key] = inline;
      else if (args[i + 1] && !args[i + 1].startsWith('--')) { out[key] = args[i + 1]; i += 1; }
      else out[key] = true;
    } else out._.push(a);
  }
  return out;
}

export const table = (headers, rows) => {
  if (rows.length === 0) return '';
  const widths = headers.map((h, i) => Math.max(h.length, ...rows.map((r) => String(r[i] ?? '').length)));
  const line = (cells) => \`| \${cells.map((c, i) => String(c ?? '').padEnd(widths[i])).join(' | ')} |\`;
  return [line(headers), \`|\${widths.map((w) => '-'.repeat(w + 2)).join('|')}|\`, ...rows.map(line)].join('\\n');
};

${spec.commands
  .map(
    (c) => `async function cmd${c.name[0].toUpperCase()}${c.name.slice(1).replace(/-([a-z])/g, (_, x) => x.toUpperCase())}(args) {
  const repo = resolve(args.repo ?? '.');
  // ${c.does}
  throw new Error('${c.name}: not implemented yet — smith scaffolded this command, the author step fills it');
}`,
  )
  .join('\n\n')}

const USAGE = \`${spec.name} v\${VERSION} — ${spec.summary}

${spec.commands.map((c) => `  ${spec.name} ${c.name} [--repo <path>]`).join('\n')}
\`;

async function main() {
  const args = argv(process.argv.slice(2));
  const cmd = args._[0];
  if (args.version) return console.log(VERSION);
  try {
    switch (cmd) {
${spec.commands
  .map(
    (c) =>
      `      case '${c.name}': return await cmd${c.name[0].toUpperCase()}${c.name.slice(1).replace(/-([a-z])/g, (_, x) => x.toUpperCase())}(args);`,
  )
  .join('\n')}
      default:
        console.log(USAGE);
        process.exitCode = cmd ? 2 : 0;
    }
  } catch (err) {
    console.error(\`${spec.name}: \${err.message}\`);
    process.exitCode = 1;
  }
}

main();
`;

/**
 * The contract test. Fully generated and green on the first run — it asserts
 * the things that rot quietly: a prose guardrail vanishing from SKILL.md, the
 * version fields drifting apart, a deterministic step naming a script nobody
 * wrote.
 */
export const contractTest = (spec) => `import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const SKILL = join(HERE, '..', '..');
const read = (p) => readFileSync(join(SKILL, p), 'utf8');
const inv = JSON.parse(read('skill-invariants.json'));

test('every prose guardrail is still in SKILL.md', () => {
  // Whitespace-normalised: a guardrail that survives intact but got re-wrapped
  // by an editor is not a lost guardrail, and a test that says otherwise
  // teaches people to weaken the patterns until it stops crying wolf.
  const md = read('SKILL.md').replace(/\\s+/g, ' ');
  for (const rule of inv.prose) {
    const pattern = rule.pattern.replace(/\\s+/g, '\\\\s+');
    assert.match(md, new RegExp(pattern, 'i'), \`\${rule.id} vanished: \${rule.rationale}\`);
  }
});

test('the declared split is real', () => {
  assert.ok(inv.split.deterministic.length > 0, 'no deterministic half declared');
  assert.ok(inv.split.nondeterministic.length > 0, 'no model-judgment half declared');
  for (const step of inv.split.deterministic) {
    const file = String(step.command).match(/scripts\\/[\\w./-]+/)?.[0];
    assert.ok(file && existsSync(join(SKILL, file)), \`deterministic step "\${step.step}" names no real script\`);
  }
});

test('version fields are in lockstep', () => {
  const pkg = JSON.parse(read('package.json')).version;
  const plugin = JSON.parse(read('../../.claude-plugin/plugin.json')).version;
  const fm = read('SKILL.md').match(/^version:\\s*(\\S+)/m)?.[1];
  assert.equal(pkg, plugin, 'package.json and plugin.json disagree');
  assert.equal(pkg, fm, 'package.json and SKILL.md frontmatter disagree');
});
`;

/**
 * The baseline test, deliberately RED until a real run is frozen.
 *
 * This is the rung-3 gate made structural. A skill cannot reach a green
 * \`npm test\` — and therefore cannot pass its own \`ci / <name>\` check — until
 * someone has actually run it and \`smith freeze\` has turned that run into
 * fixtures. Nothing else in the toolchain can tell a real eval from an
 * aspirational one, so the scaffold refuses to be green about it.
 */
export const baselineTestStub = (spec) => `import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const BASELINE = join(HERE, '..', '..', 'evals', 'baseline');

// ---------------------------------------------------------------------------
// NOT YET FROZEN. ${spec.name} has no baseline until it has actually been run.
//
// Run the skill end to end on a real input, then:
//     smith freeze --skill ${spec.name} --from <the run's output dir>
//
// which replaces this file with assertions over what that run really produced.
// Deleting this test to get green is the one shortcut that makes every other
// gate in this repo decorative.
// ---------------------------------------------------------------------------
test('a real run has been frozen as the baseline', () => {
  assert.ok(
    existsSync(join(BASELINE, 'MANIFEST.json')),
    'no real run frozen yet — ${spec.name} is at rung 2 (scaffolded and lint-clean), not rung 3. Run it for real, then \`smith freeze\`.',
  );
});
`;

export const referenceStub = (spec, ref) => `# ${ref.file.replace(/\.md$/, '')}

${ref.is}

> Scaffolded by smith. This file is part of ${spec.name}'s contract — SKILL.md
> points at it, so it must say something real before the skill ships.
`;

/* ------------------------------------------------------------------ CI caller */

/**
 * The caller workflow, in the house shape. Two properties are load-bearing and
 * are the reason this is generated rather than copied by hand:
 *
 *   - the `pull_request` trigger is UN-filtered, so `ci / <name>` reports on
 *     every PR and the required-check set stays satisfiable for a dev -> main
 *     promotion no matter which skills it touched;
 *   - `permissions: pull-requests: read` is what lets dorny/paths-filter see
 *     changes under the restricted default token. Dropping it red-lines the
 *     required check on every PR.
 *
 * Action pins come from `readActionPins` — the SHAs this repo already trusts,
 * never a remembered one.
 */
export const caller = (spec, pins) => {
  const pin = (a) => pins[a] ?? `# UNRESOLVED — run: forge resolve ${a}`;
  const setup =
    spec.stack === 'node'
      ? `      - if: steps.changes.outputs.${spec.name} == 'true'
        uses: actions/setup-node@${pin('actions/setup-node')}
        with:
          node-version: "22"
`
      : `      - if: steps.changes.outputs.${spec.name} == 'true'
        uses: actions/setup-python@${pin('actions/setup-python')}
        with:
          python-version: "3.12"
`;

  const tier2 =
    spec.stack === 'node'
      ? `      - if: steps.changes.outputs.${spec.name} == 'true'
        run: npm install --no-fund
        working-directory: skills/${spec.name}/skills/${spec.name}

      - if: steps.changes.outputs.${spec.name} == 'true'
        run: npm test
        working-directory: skills/${spec.name}/skills/${spec.name}

      - if: steps.changes.outputs.${spec.name} == 'true'
        run: npm run audit
        working-directory: skills/${spec.name}/skills/${spec.name}
`
      : `      - if: steps.changes.outputs.${spec.name} == 'true'
        run: pip install -r requirements-dev.txt
        working-directory: skills/${spec.name}/skills/${spec.name}

      - if: steps.changes.outputs.${spec.name} == 'true'
        run: python -m pytest
        working-directory: skills/${spec.name}/skills/${spec.name}
`;

  return `name: ${spec.name}

# Per-skill CI + release for the ${spec.name} skill. The \`pull_request\` trigger is
# deliberately UN-filtered so \`ci / ${spec.name}\` reports on every PR — running real
# tests when this skill changed and short-circuiting to success when it didn't —
# which is what keeps the required-check set always satisfiable for a dev -> main
# PR. The \`push\` trigger IS path-filtered so the skill only releases when its own
# files changed.
on:
  push:
    branches: [main]
    paths:
      - "skills/${spec.name}/**"
      - "tools/score_skill.py"
      - "tools/lint_plugin.py"
      - ".github/workflows/${spec.name}.yml"
  pull_request:
    branches: [dev, main, 'feature/**']
  workflow_dispatch:

jobs:
  ci:
    name: ci / ${spec.name}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@${pin('actions/checkout')}
        with:
          persist-credentials: false

      - name: Detect relevant changes
        id: changes
        uses: dorny/paths-filter@${pin('dorny/paths-filter')}
        with:
          filters: |
            ${spec.name}:
              - 'skills/${spec.name}/**'
              - 'skills/press/skills/press/**'
              - 'tools/score_skill.py'
              - 'tools/lint_plugin.py'
              - '.github/workflows/${spec.name}.yml'

      - if: steps.changes.outputs.${spec.name} == 'true'
        uses: actions/setup-python@${pin('actions/setup-python')}
        with:
          python-version: "3.12"

${spec.stack === 'node' ? setup : ''}
      # Tier 1 — the SKILL.md lint
      - if: steps.changes.outputs.${spec.name} == 'true'
        run: python tools/score_skill.py skills/${spec.name}/skills/${spec.name} --min 100

      # Tier 1.5 — plugin manifest / version tie
      - if: steps.changes.outputs.${spec.name} == 'true'
        run: python tools/lint_plugin.py skills/${spec.name}

      # Tier 1.6 — brand drift, this skill's regions only
      - if: steps.changes.outputs.${spec.name} == 'true'
        run: node skills/press/skills/press/bin/press.js check --repo . --target ${spec.name}-agent-ui --target ${spec.name}-readme

      # Tier 2 — ${spec.name}'s own suite. Offline and $0 by construction: the
      # baseline never calls the network, so CI cannot spend and cannot flake.
${tier2}
  release:
    needs: ci
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    uses: ./.github/workflows/_release.yml
    with:
      skill: ${spec.name}${spec.npmPublish ? '\n      npm-publish: true' : ''}
    permissions:
      contents: write
`;
};
