import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {createRun,saveRun} from '../lib/run.mjs';import {ensureWorktree} from '../lib/worktree.mjs';import {proposePublishedAmendment,applyPublishedAmendment} from '../lib/published-amendment.mjs';import {hash} from '../lib/contracts.mjs';
const git=(cwd,...args)=>execFileSync('git',args,{cwd,encoding:'utf8',stdio:'pipe'}).trim();
function fixture(t){const root=mkdtempSync(join(tmpdir(),'issueflow-retarget-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const repo=join(root,'repo'),dir=join(root,'run');mkdirSync(repo);git(repo,'init','-qb','dev');git(repo,'config','user.name','test');git(repo,'config','user.email','test@example.invalid');writeFileSync(join(repo,'answer.cjs'),'module.exports=41;\n');git(repo,'add','.');git(repo,'commit','-qm','base');const base=git(repo,'rev-parse','HEAD');const run=createRun({strict:true,repo:{owner:'local',name:'retarget',path:repo},issue:{number:1,title:'answer'},policy:{base:'dev',featurePrefix:'feature/'},offline:true});run.harness.bases.root=base;run.harness.contract={schema:1,risk:'standard',criteria:[{id:'C1',description:'returns 42'}],nonGoals:[],allowedPaths:['answer.cjs','answer.test.cjs'],checks:[{id:'regression',type:'regression',argv:[process.execPath,'--test','answer.test.cjs'],testFiles:['answer.test.cjs'],criteria:['C1']}]};run.harness.contractHash=hash(run.harness.contract);run.stages[0].state='approved';saveRun(dir,run);const lane=run.lanes[0];const tree=ensureWorktree(repo,dir,lane,{offline:true,lanes:run.lanes}).path;writeFileSync(join(tree,'answer.cjs'),'module.exports=42;\n');git(tree,'commit','-qam','fix');lane.pr={number:1,url:'https://example.invalid/1'};lane.review.rounds=[{round:1,head:git(tree,'rev-parse','HEAD'),registered:true,verdict:'converged'}];lane.review.converged=true;saveRun(dir,run);git(repo,'checkout','-qb','main');writeFileSync(join(repo,'unrelated.txt'),'upstream\n');git(repo,'add','.');git(repo,'commit','-qm','upstream');const plan='# Plan\n\n## Files\nanswer.cjs, answer.test.cjs\n\n```issueflow-contract\n'+JSON.stringify(run.harness.contract)+'\n```\n';return {root,repo,dir,run,lane,tree,base,plan};}
test('retarget target-only refuses upstream contamination; reviewed Git merge candidate keeps the original lane untouched',t=>{
 const f=fixture(t),head=git(f.tree,'rev-parse','HEAD'),before=readFileSync(join(f.dir,'run.json'),'utf8');const options={plan:f.plan,base:'main',reason:'User selected main',authoritySource:'message 2',workersReleased:true};
 assert.throws(()=>proposePublishedAmendment(f.dir,f.run,options),/unapproved paths/);assert.equal(readFileSync(join(f.dir,'run.json'),'utf8'),before);
 const entry=proposePublishedAmendment(f.dir,f.run,{...options,strategy:'merge'});assert.equal(git(f.tree,'rev-parse','HEAD'),head);assert.equal(f.lane.base,'dev');assert.notEqual(entry.lanes[0].candidateHead,head);assert.equal(git(entry.lanes[0].candidateTree,'merge-base',entry.lanes[0].candidateHead,entry.lanes[0].baseSha),entry.lanes[0].baseSha);
 assert.throws(()=>applyPublishedAmendment(f.dir,f.run,{workersReleased:true}),/passing independent review/);
});
test('retarget refuses dirty work and exhausted review caps before Git changes',t=>{
 const f=fixture(t),options={plan:f.plan,base:'main',reason:'selected main',authoritySource:'message 2',workersReleased:true,strategy:'merge'};writeFileSync(join(f.tree,'answer.cjs'),'uncommitted');assert.throws(()=>proposePublishedAmendment(f.dir,f.run,options),/dirty/);assert.equal(readFileSync(join(f.tree,'answer.cjs'),'utf8'),'uncommitted');
 f.lane.review.maxRounds=1;assert.throws(()=>proposePublishedAmendment(f.dir,f.run,options),/capacity is exhausted/);
});

test('CLI retarget proposes the reviewed base transition and requires a concrete plan',t=>{
 const f=fixture(t),cli=fileURLToPath(new URL('../issueflow.js',import.meta.url)),planFile=join(f.root,'plan.md');writeFileSync(planFile,f.plan);
 const output=execFileSync(process.execPath,[cli,'retarget','--run-dir',f.dir,'--plan',planFile,'--base','main','--strategy','merge','--reason','selected main','--authority-source','user message 2','--workers-released'],{encoding:'utf8'});
 assert.match(output,/Amendment .* proposed/);assert.equal(JSON.parse(readFileSync(join(f.dir,'run.json'),'utf8')).lanes[0].base,'dev');
 assert.throws(()=>execFileSync(process.execPath,[cli,'retarget','--run-dir',f.dir,'--workers-released','--reason','missing plan'],{encoding:'utf8',stdio:'pipe'}),error=>/retarget requires --plan and --base/.test(error.stderr));
});
