/**
 * The baseline eval — offline, deterministic, $0.
 *
 * Pinned against a real run: `evals/baseline/broken.yml` and `good.yml` are the
 * exact files the ladder was developed against, and the defect counts below are
 * what the real tools actually reported on them. Nothing here calls the network
 * or a model — CI must never spend, and a gate that flakes stops gating.
 *
 * Two-sided throughout: the good file must pass every parser AND the broken file
 * must fail on each rung it should. A one-sided baseline goes quietly green the
 * day someone weakens a checker.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { collectUses } from '../lib/verify.mjs';
import { parseUses } from '../lib/resolve.mjs';
import { headerBody, renderHeader } from '../lib/header.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const BASE = join(HERE, '../evals/baseline');
const WORKFLOWS = join(HERE, '../../../../../.github/workflows');

const good = readFileSync(join(BASE, 'good.yml'), 'utf8');
const broken = readFileSync(join(BASE, 'broken.yml'), 'utf8');

// --- anti-vacuity ---------------------------------------------------------

test('the frozen fixtures are still real workflows, not empty files', () => {
  for (const [name, text] of [['good', good], ['broken', broken]]) {
    assert.ok(text.includes('jobs:'), `${name}.yml has no jobs block`);
    assert.ok(text.split('\n').length >= 10, `${name}.yml shrank to nothing`);
  }
});

/**
 * The corpus floor. `collectUses` is the front door of rung 0 — if it silently
 * matched nothing, every downstream check would report "all clean" while
 * verifying zero actions. That exact failure mode (a checker that passes because
 * it examined nothing) is why this floor exists.
 */
test('collectUses finds real action references across this repo, above a floor', () => {
  const files = readdirSync(WORKFLOWS).filter((f) => /\.ya?ml$/.test(f));
  assert.ok(files.length >= 12, `only ${files.length} workflows — the corpus shrank`);

  let total = 0;
  for (const f of files) total += collectUses(readFileSync(join(WORKFLOWS, f), 'utf8')).length;
  assert.ok(total >= 20, `only ${total} uses found across ${files.length} workflows — parser regressed`);
});

// --- rung 0: the parser, two-sided ---------------------------------------

test('every uses: in the good fixture parses to a real owner/repo/ref', () => {
  const found = collectUses(good);
  assert.equal(found.length, 2, 'the good fixture has exactly two actions');
  for (const u of found) {
    const p = parseUses(u.uses);
    assert.equal(p.kind, 'action');
    assert.ok(p.owner && p.repo && p.ref, u.uses);
  }
});

test('the broken fixture still carries every defect class it was frozen for', () => {
  const uses = collectUses(broken).map((u) => u.uses);
  assert.ok(uses.some((u) => u.endsWith('@v99')), 'lost the dead-ref case');
  assert.ok(uses.some((u) => u.includes('setup-nodejs')), 'lost the nonexistent-action case');
  assert.ok(broken.includes('node_version'), 'lost the misspelled-input case');
  assert.ok(broken.includes('${{ github.event.pull_request.title }}'), 'lost the injection case');
  assert.ok(broken.includes('set-output'), 'lost the deprecated-command case');
});

/**
 * The `with:` keys are what rung 0 checks against the action's real `action.yml`.
 * Mis-associating them would make input validation silently vacuous — it would
 * check an empty key list and always pass.
 */
test('with: keys are attributed to the step that declared them', () => {
  const found = collectUses(broken);
  // Matched exactly: `includes('setup-node')` also matches `setup-nodejs`, which
  // is the neighbouring fixture case — and picking it up silently asserted the
  // wrong step's (empty) key list.
  const setupNode = found.find((u) => u.uses === 'actions/setup-node@v4');
  assert.deepEqual(setupNode.withKeys, ['node_version']);
  const checkout = found.find((u) => u.uses.startsWith('actions/checkout@'));
  assert.deepEqual(checkout.withKeys, [], 'a step with no with: must not inherit the next step\'s');
});

/**
 * Staleness rides on the trailing comment for SHA pins. Losing it would make the
 * recommended pin format the one format staleness cannot be seen in — which is
 * how a workflow sits two majors behind with a fully green gate.
 */
test('the trailing version comment on a SHA pin is captured', () => {
  const found = collectUses(good);
  assert.deepEqual(found.map((u) => u.comment), ['v5', 'v4']);
});

// --- the masthead: byte-exact ---------------------------------------------

/**
 * Byte-exactness is used deliberately and rarely. It is right here for the same
 * reason it is right for shipflow's rendered workflow and press's emitted
 * regions: the generated bytes ARE the contract. One changed character is a
 * change to what every generated workflow looks like.
 *
 * The BODY is frozen, not the whole block: the start marker carries press's
 * version, so pinning it would make every press release fail forge's CI over a
 * change that altered nothing forge emits — the same "a version bump is not a
 * content change" distinction press's own propagate classification draws.
 *
 * Refresh: node evals/baseline/update.mjs
 */
test('the masthead renders exactly as frozen', async () => {
  const frozen = readFileSync(join(BASE, 'masthead.txt'), 'utf8').replace(/\n$/, '');
  const actual = await headerBody({
    title: 'CI · node test',
    purpose: 'Lint and test on every pull request into main.',
    generatorVersion: '0.1.0',
  });
  assert.equal(
    actual,
    frozen,
    'masthead drifted — if this is intended, refresh with: node evals/baseline/update.mjs',
  );
});

test('the masthead is entirely comment lines, so a workflow still parses', async () => {
  const block = await renderHeader({
    title: 'CI', purpose: 'x', generatorVersion: '0.1.0',
  });
  const bare = block.split('\n').filter((l) => !l.startsWith('#'));
  assert.deepEqual(bare, [], 'a non-comment line would be spliced into the YAML document');
});

/**
 * The gate must refuse to pass on nothing. With no files, bare `actionlint`
 * auto-discovers `.github/workflows` and would report clean about workflows the
 * caller never named — the exact way a checker turns decorative.
 */
test('verify refuses to run against zero files', async () => {
  const { verify, VerifyError } = await import('../lib/verify.mjs');
  await assert.rejects(() => verify([], []), VerifyError);
});
