/**
 * Demo mode for the preview app.
 *
 * When the user runs the preview without env vars (or without going through
 * `npx @natjswenson/devlog init`), we render fake entries against a
 * pretend GitHub URL. The real DevLogPage component does its normal thing;
 * a tiny fetch override intercepts requests to the demo URL and serves
 * canned data.
 *
 * Goal: show the user what their dev log will look like, while loudly
 * encouraging them to wipe this out and point it at their real repo.
 */

export const DEMO_BASE = 'https://demo-mode.local';
export const DEMO_PROJECT_KEY = 'placeholder-empire';
export const DEMO_PROJECTS = [
  { key: DEMO_PROJECT_KEY, label: 'The Placeholder Empire' },
];

function offsetDate(daysAgo) {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().slice(0, 10);
}

const ENTRIES = [
  {
    date: offsetDate(0),
    title: 'You are looking at fake data',
    summary: "Hi. These aren't your entries. Your entries are 30 seconds away.",
    body: `## What I Built

Nothing. I'm a placeholder. A handsome one, but still a placeholder.

You're seeing this screen because the preview app couldn't find env vars
pointing at your dev-log repo. Once that's fixed, this entire feed gets
replaced with real entries, generated by the \`/devlog\` skill from your
actual git commits.

## What's Next

You. Setting things up. Probably while half-watching a YouTube tutorial
about something unrelated. We believe in you.

## Public Commits

- [demo] make placeholder more passive-aggressive ([abcd123](#))
- [demo] add a tiny bit of charm ([def4567](#))
`,
  },
  {
    date: offsetDate(1),
    title: 'How to make this screen go away',
    summary: 'Two paths: the lazy one (recommended) and the manual one (also fine).',
    body: `## The lazy path

\`\`\`sh
npx @natjswenson/devlog init
\`\`\`

Answer four prompts. The CLI creates your dev-log repo on GitHub, installs
the Claude Code skill, and writes your config. Run \`npx @natjswenson/devlog preview\`
again. This entry vanishes. You feel powerful.

## The manual path

Set these in \`preview/.env.local\` (or your shell), then restart vite:

\`\`\`
VITE_DEVLOG_OWNER=your-github-username
VITE_DEVLOG_REPO=daily-dev-log
VITE_DEVLOG_BRANCH=main
VITE_DEVLOG_PROJECTS=[{"key":"myproject","label":"My Project"}]
\`\`\`

## What's Next

The real preview, with your real entries. Try it.
`,
  },
  {
    date: offsetDate(3),
    title: "Why you'd actually want this",
    summary: 'Build in public, but with style. And without remembering to write blog posts.',
    body: `## What I Built

The whole point: you commit code as usual. You run \`/devlog\` in Claude Code.
The skill reads today's commits and writes a *narrative* entry — not "fix typo,
fix typo again, ok actually fix it" but real prose about what you built and why.

That entry gets pushed to your dev-log repo. Your site (or this preview app,
deployed to Vercel/Netlify/Cloudflare) renders it.

The result: you ship in public without ever opening a blog post editor.

## What's Next

You'll set this up. You'll ship something on day one. You'll feel slightly
smug about it on the train tomorrow. We're rooting for you.

## Public Commits

- [demo] write hopeful pep talk ([eeee101](#))
`,
  },
  {
    date: offsetDate(7),
    title: "Things this is not",
    summary: 'A short list, for the avoidance of disappointment.',
    body: `## Not features

- A blog CMS. There are sixty of those. Use one if you want one.
- A social network. Please don't.
- An AI ghostwriter for marketing copy. The narratives come from *your*
  commits. Garbage in, garbage out.
- A way to make your past coding choices look better in retrospect. Sorry.

## Is features

- A way to ship dev log entries without context-switching out of Claude Code.
- A static, no-backend pipeline (manifest.json + markdown on GitHub).
- Components you can drop into your own React site, or the preview app you
  can deploy as a standalone dev log.

## What's Next

Replace this fake entry with a real one. It's right there. Just go.
`,
  },
];

const MANIFEST = {
  entries: ENTRIES.map((e) => ({
    date: e.date,
    file: `${e.date}.md`,
    title: e.title,
    summary: e.summary,
  })),
};

function entryMarkdown(entry) {
  return `---
title: "${entry.title.replace(/"/g, '\\"')}"
date: ${entry.date}
project: ${DEMO_PROJECT_KEY}
summary: "${entry.summary.replace(/"/g, '\\"')}"
---

${entry.body}`;
}

function demoResponse(url) {
  if (url.endsWith('manifest.json')) {
    return new Response(JSON.stringify(MANIFEST), {
      status: 200,
      headers: { 'content-type': 'application/json' },
    });
  }
  const m = url.match(/(\d{4}-\d{2}-\d{2})\.md$/);
  if (m) {
    const entry = ENTRIES.find((e) => e.date === m[1]);
    if (entry) {
      return new Response(entryMarkdown(entry), {
        status: 200,
        headers: { 'content-type': 'text/plain' },
      });
    }
  }
  return new Response('demo: not found', { status: 404 });
}

export function installDemoFetch() {
  const original = window.fetch.bind(window);
  window.fetch = async (input, init) => {
    const url = typeof input === 'string' ? input : input?.url || String(input);
    if (url.startsWith(DEMO_BASE)) {
      return demoResponse(url);
    }
    return original(input, init);
  };
}
